name: Deploy Hugo to S3

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"

      - name: Build site
        run: hugo --minify

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::001945408634:role/GithubS3Deploy"
          aws-region: "eu-central-1"

      - name: Sync to S3
        run: aws s3 sync public "s3://davvi-website" --delete

#      - name: Invalidate CloudFront cache
#        run: aws cloudfront create-invalidation --distribution-id "E2K5ARG5BGZSL7" --paths "/*"
